apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: food
        image: sajidqureshi/ecommerce:food-v1
        ports:
        - containerPort: 8080
