apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - name: video
        image: sajidqureshi/ecommerce:video-v1
        ports:
        - containerPort: 8080
